[2024-09-13 01:04:41] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:04:52] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:04:52] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 79469
[2024-09-13 01:04:52] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:04:52] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 2911
[2024-09-13 01:05:10] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/to_do_list/settings.py changed, reloading.
[2024-09-13 01:05:10] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:05:14] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:05:14] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 0
[2024-09-13 01:05:27] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:05:32] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:05:32] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 594
[2024-09-13 01:05:32] [INFO] [django.server:212] "GET /static/css/404.b12af72df915.css HTTP/1.1" 200 316
[2024-09-13 01:05:32] [INFO] [django.server:212] "GET /static/js/404.886b4f9785a3.js HTTP/1.1" 200 279
[2024-09-13 01:12:14] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:12:20] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:12:20] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 671
[2024-09-13 01:12:20] [INFO] [django.server:212] "GET /static/css/404.ba57d21e39c0.css HTTP/1.1" 200 461
[2024-09-13 01:12:20] [INFO] [django.server:212] "GET /static/js/404.886b4f9785a3.js HTTP/1.1" 200 279
[2024-09-13 01:12:20] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:12:20] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 671
[2024-09-13 01:16:26] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:16:29] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:16:29] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 671
[2024-09-13 01:16:29] [INFO] [django.server:212] "GET /static/css/404.63c14406bcf9.css HTTP/1.1" 200 498
[2024-09-13 01:16:33] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:16:33] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 671
[2024-09-13 01:18:43] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:18:48] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:18:48] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 677
[2024-09-13 01:18:48] [INFO] [django.server:212] "GET /static/css/404.1f8657c3e935.css HTTP/1.1" 200 495
[2024-09-13 01:21:37] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:21:42] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:21:42] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 677
[2024-09-13 01:21:42] [INFO] [django.server:212] "GET /static/css/404.cbbe0868ea3f.css HTTP/1.1" 200 523
[2024-09-13 01:21:42] [INFO] [django.server:212] "GET /static/js/404.886b4f9785a3.js HTTP/1.1" 200 279
[2024-09-13 01:21:42] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:21:42] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 677
[2024-09-13 01:22:53] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:22:53] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 0
[2024-09-13 01:33:03] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:33:12] [WARNING] [django.request:241] Not Found: /dadasd
[2024-09-13 01:33:12] [WARNING] [django.server:212] "GET /dadasd HTTP/1.1" 404 677
[2024-09-13 01:33:12] [INFO] [django.server:212] "GET /static/css/404.e6b0fe855dd5.css HTTP/1.1" 200 527
[2024-09-13 01:33:16] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:33:16] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 856
[2024-09-13 01:33:16] [INFO] [django.server:212] "GET /static/css/500.dc8487fe28f3.css HTTP/1.1" 200 800
[2024-09-13 01:33:16] [INFO] [django.server:212] "GET /static/js/500.61e0d794c346.js HTTP/1.1" 200 428
[2024-09-13 01:38:57] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:39:01] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:39:01] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 856
[2024-09-13 01:39:01] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 01:39:01] [INFO] [django.server:212] "GET /static/js/500.61e0d794c346.js HTTP/1.1" 200 428
[2024-09-13 01:39:01] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:39:01] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 677
[2024-09-13 01:44:52] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:45:01] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:45:01] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 856
[2024-09-13 01:45:01] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 01:45:01] [INFO] [django.server:212] "GET /static/js/500.8c1a1a9829f9.js HTTP/1.1" 200 442
[2024-09-13 01:45:01] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:45:01] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 677
[2024-09-13 01:45:48] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:45:48] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 943
[2024-09-13 01:45:51] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:45:51] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 943
[2024-09-13 01:45:51] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 01:45:51] [INFO] [django.server:212] "GET /static/js/500.8c1a1a9829f9.js HTTP/1.1" 200 442
[2024-09-13 01:45:52] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:45:52] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 677
[2024-09-13 01:46:27] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:46:31] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:46:31] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 943
[2024-09-13 01:46:31] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 01:46:31] [INFO] [django.server:212] "GET /static/js/500.61e0d794c346.js HTTP/1.1" 200 428
[2024-09-13 01:46:31] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 01:46:31] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 677
[2024-09-13 01:55:07] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 01:55:19] [WARNING] [django.request:241] Not Found: /homesdadss/
[2024-09-13 01:55:19] [WARNING] [django.server:212] "GET /homesdadss/ HTTP/1.1" 404 1163
[2024-09-13 01:55:19] [INFO] [django.server:212] "GET /static/fav/site.b9aa277fcfc3.webmanifest HTTP/1.1" 200 147
[2024-09-13 01:55:19] [INFO] [django.server:212] "GET /static/fav/favicon-32x32.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 01:55:27] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 01:55:27] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1429
[2024-09-13 01:55:27] [INFO] [django.server:212] "GET /static/js/500.3409e1481f8d.js HTTP/1.1" 200 455
[2024-09-13 02:24:15] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 302 0
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4272
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/css/base.64976e0f7339.css HTTP/1.1" 200 4149
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/css/dark_mode.ef27a31af300.css HTTP/1.1" 200 669
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/css/nav_sidebar.269a1bd44627.css HTTP/1.1" 200 625
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/css/responsive.107cd2690311.css HTTP/1.1" 200 2963
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/js/theme.ab270f56bb9c.js HTTP/1.1" 200 501
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/js/nav_sidebar.3b9190d420b1.js HTTP/1.1" 200 690
[2024-09-13 02:24:24] [INFO] [django.server:212] "GET /static/admin/css/login.586129c60a93.css HTTP/1.1" 200 310
[2024-09-13 02:24:24] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 02:24:24] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 1163
[2024-09-13 02:24:31] [INFO] [django.server:212] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2024-09-13 02:24:31] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 02:24:31] [INFO] [django.server:212] "GET /static/admin/css/dashboard.e90f2068217b.css HTTP/1.1" 200 185
[2024-09-13 02:24:31] [INFO] [django.server:212] "GET /static/admin/img/icon-addlink.d519b3bab011.svg HTTP/1.1" 200 178
[2024-09-13 02:24:31] [INFO] [django.server:212] "GET /static/admin/img/icon-changelink.18d2fd706348.svg HTTP/1.1" 200 252
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11592
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/css/changelists.9237a1ac391b.css HTTP/1.1" 200 1274
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/core.cf103cd04ebf.js HTTP/1.1" 200 1278
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/admin/RelatedObjectLookups.8609f99b9ab2.js HTTP/1.1" 200 1946
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/jquery.init.b7781a0897fc.js HTTP/1.1" 200 194
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/vendor/jquery/jquery.min.641dd1437010.js HTTP/1.1" 200 28035
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/actions.eac7e3441574.js HTTP/1.1" 200 1614
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/prepopulate.bd2361dfd64d.js HTTP/1.1" 200 468
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/urlify.ae970a820212.js HTTP/1.1" 200 1969
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/vendor/xregexp/xregexp.min.b0439563a5d3.js HTTP/1.1" 200 21896
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/js/filters.0e360b7a9f80.js HTTP/1.1" 200 392
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/img/search.7cf54ff789c6.svg HTTP/1.1" 200 241
[2024-09-13 02:24:36] [INFO] [django.server:212] "GET /static/admin/img/tooltag-add.e59d620a9742.svg HTTP/1.1" 200 182
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /admin/service/userprofile/1/change/ HTTP/1.1" 200 13668
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/css/forms.3b181cba6653.css HTTP/1.1" 200 1879
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/js/admin/DateTimeShortcuts.9f6e209cebca.js HTTP/1.1" 200 3030
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/js/prepopulate_init.6cac7f3105b8.js HTTP/1.1" 200 231
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/js/change_form.9d8ca4f96b75.js HTTP/1.1" 200 243
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/js/calendar.f8a5d055eb33.js HTTP/1.1" 200 1826
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/img/icon-viewlink.41eb31f7826e.svg HTTP/1.1" 200 326
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/css/widgets.0a3765e806b3.css HTTP/1.1" 200 2142
[2024-09-13 02:24:38] [INFO] [django.server:212] "GET /static/admin/img/icon-calendar.ac7aea671bea.svg HTTP/1.1" 200 411
[2024-09-13 02:24:43] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 9854
[2024-09-13 02:24:43] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:46] [INFO] [django.server:212] "GET /admin/service/task/add/ HTTP/1.1" 200 12002
[2024-09-13 02:24:46] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:52] [INFO] [django.server:212] "GET /admin/service/faq/ HTTP/1.1" 200 9466
[2024-09-13 02:24:52] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:54] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9667
[2024-09-13 02:24:54] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 02:24:57] [INFO] [django.server:212] "GET /admin/service/faq/ HTTP/1.1" 200 9466
[2024-09-13 02:25:00] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 02:25:00] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 1429
[2024-09-13 02:25:00] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 02:25:00] [INFO] [django.server:212] "GET /static/js/500.3409e1481f8d.js HTTP/1.1" 200 455
[2024-09-13 02:25:01] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 02:25:05] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 8, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 02:25:05] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 1429
[2024-09-13 02:25:05] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 02:25:05] [INFO] [django.server:212] "GET /static/js/500.3409e1481f8d.js HTTP/1.1" 200 455
[2024-09-13 02:25:05] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 15:27:22] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 15:27:26] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 15:27:26] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 1482
[2024-09-13 15:27:26] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 15:27:35] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 15:27:56] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 15:27:56] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 1492
[2024-09-13 15:27:56] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-13 15:28:03] [WARNING] [django.request:241] Not Found: /dasdsa
[2024-09-13 15:28:03] [WARNING] [django.server:212] "GET /dasdsa HTTP/1.1" 404 1169
[2024-09-13 15:28:03] [INFO] [django.server:212] "GET /static/css/404.e6b0fe855dd5.css HTTP/1.1" 200 527
[2024-09-13 15:28:08] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 15:28:08] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-13 16:12:53] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:12:57] [ERROR] [django.request:241] Internal Server Error: /
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 16:12:57] [ERROR] [django.server:212] "GET / HTTP/1.1" 500 1492
[2024-09-13 16:12:57] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-13 16:12:57] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:12:57] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-13 16:13:03] [WARNING] [django.request:241] Not Found: /login/
[2024-09-13 16:13:03] [WARNING] [django.server:212] "GET /login/ HTTP/1.1" 404 1169
[2024-09-13 16:13:17] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/urls.py changed, reloading.
[2024-09-13 16:13:17] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:13:20] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 302 0
[2024-09-13 16:13:20] [INFO] [django.server:212] "GET /home HTTP/1.1" 301 0
[2024-09-13 16:13:20] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 16:13:20] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/css/base.64976e0f7339.css HTTP/1.1" 200 4149
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/css/dark_mode.ef27a31af300.css HTTP/1.1" 200 669
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/css/dashboard.e90f2068217b.css HTTP/1.1" 200 185
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/css/responsive.107cd2690311.css HTTP/1.1" 200 2963
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/css/nav_sidebar.269a1bd44627.css HTTP/1.1" 200 625
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/img/icon-addlink.d519b3bab011.svg HTTP/1.1" 200 178
[2024-09-13 16:13:38] [INFO] [django.server:212] "GET /static/admin/img/icon-changelink.18d2fd706348.svg HTTP/1.1" 200 252
[2024-09-13 16:13:38] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 16:13:38] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 1169
[2024-09-13 16:13:41] [INFO] [django.server:212] "POST /admin/logout/ HTTP/1.1" 200 3654
[2024-09-13 16:13:45] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4542
[2024-09-13 16:13:45] [INFO] [django.server:212] "GET /static/css/login.c95d5aa912b0.css HTTP/1.1" 200 1129
[2024-09-13 16:13:45] [INFO] [django.server:212] "GET /static/js/login.b05909b830db.js HTTP/1.1" 200 1516
[2024-09-13 16:14:05] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4542
[2024-09-13 16:14:05] [INFO] [django.server:212] "GET /static/css/login.c95d5aa912b0.css HTTP/1.1" 200 1129
[2024-09-13 16:14:05] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:14:05] [INFO] [django.server:212] "GET /static/js/login.b05909b830db.js HTTP/1.1" 200 1516
[2024-09-13 16:14:06] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 16:15:04] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:20:07] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:20:10] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:20:10] [INFO] [django.server:212] "GET /static/css/login.1c0cc8c804f6.css HTTP/1.1" 200 1148
[2024-09-13 16:22:09] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:22:11] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:22:11] [INFO] [django.server:212] "GET /static/css/login.1721c969e6c5.css HTTP/1.1" 200 1134
[2024-09-13 16:22:11] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:22:11] [INFO] [django.server:212] "GET /static/js/login.b05909b830db.js HTTP/1.1" 200 1516
[2024-09-13 16:22:12] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 16:23:23] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4549
[2024-09-13 16:24:01] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4549
[2024-09-13 16:24:02] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4549
[2024-09-13 16:24:02] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4549
[2024-09-13 16:24:20] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:26:58] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:27:01] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:27:01] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-13 16:27:01] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:30:15] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:30:19] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:30:19] [INFO] [django.server:212] "GET /static/js/login.e716d2428053.js HTTP/1.1" 200 1528
[2024-09-13 16:30:21] [WARNING] [django.request:241] Bad Request: /login_api/
[2024-09-13 16:30:21] [WARNING] [django.server:212] "POST /login_api/ HTTP/1.1" 400 41
[2024-09-13 16:33:53] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:33:56] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:33:56] [INFO] [django.server:212] "GET /static/js/login.e1e08cd265ab.js HTTP/1.1" 200 1528
[2024-09-13 16:34:10] [ERROR] [django.request:241] Internal Server Error: /signup_api/
[2024-09-13 16:34:10] [ERROR] [django.server:212] "POST /signup_api/ HTTP/1.1" 500 93
[2024-09-13 16:34:15] [WARNING] [django.request:241] Bad Request: /login_api/
[2024-09-13 16:34:15] [WARNING] [django.server:212] "POST /login_api/ HTTP/1.1" 400 41
[2024-09-13 16:39:37] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py changed, reloading.
[2024-09-13 16:39:37] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:40:02] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 16:40:02] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:40:20] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 16:40:20] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:40:41] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:40:49] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:40:50] [WARNING] [django.request:241] Bad Request: /login_api/
[2024-09-13 16:40:50] [WARNING] [django.server:212] "POST /login_api/ HTTP/1.1" 400 61
[2024-09-13 16:40:52] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:40:52] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-13 16:40:52] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:40:52] [INFO] [django.server:212] "GET /static/js/login.e1e08cd265ab.js HTTP/1.1" 200 1528
[2024-09-13 16:40:53] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 16:41:03] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-13 16:41:03] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 16:41:03] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-13 16:41:10] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 16:41:10] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 16:41:12] [INFO] [django.server:212] "POST /admin/logout/ HTTP/1.1" 200 3654
[2024-09-13 16:41:16] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:41:34] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:41:34] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:42:57] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:43:02] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:43:02] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-13 16:43:02] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:43:02] [INFO] [django.server:212] "GET /static/js/login.e1e08cd265ab.js HTTP/1.1" 200 1528
[2024-09-13 16:43:03] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 16:43:14] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-13 16:43:14] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 16:43:14] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-13 16:43:19] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 16:43:20] [INFO] [django.server:212] "POST /admin/logout/ HTTP/1.1" 200 3654
[2024-09-13 16:43:24] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:43:40] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:43:40] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:43:51] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 302 0
[2024-09-13 16:43:51] [INFO] [django.server:212] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4272
[2024-09-13 16:43:51] [INFO] [django.server:212] "GET /static/admin/css/login.586129c60a93.css HTTP/1.1" 200 310
[2024-09-13 16:43:51] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-13 16:43:51] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 1169
[2024-09-13 16:44:00] [INFO] [django.server:212] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2024-09-13 16:44:00] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 16:44:02] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11694
[2024-09-13 16:44:02] [INFO] [django.server:212] "GET /static/admin/js/vendor/jquery/jquery.min.641dd1437010.js HTTP/1.1" 200 28035
[2024-09-13 16:44:02] [INFO] [django.server:212] "GET /static/admin/js/vendor/xregexp/xregexp.min.b0439563a5d3.js HTTP/1.1" 200 21896
[2024-09-13 16:44:03] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:44:05] [ERROR] [django.request:241] Internal Server Error: /admin/service/userprofile/2/change/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py", line 24, in __str__
    return f"{self.name} {self.last_name}"
AttributeError: 'UserProfile' object has no attribute 'last_name'
[2024-09-13 16:44:06] [ERROR] [django.server:212] "GET /admin/service/userprofile/2/change/ HTTP/1.1" 500 1492
[2024-09-13 16:44:06] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:44:06] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-13 16:44:11] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11694
[2024-09-13 16:44:15] [ERROR] [django.request:241] Internal Server Error: /admin/service/userprofile/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1959, in changelist_view
    response = self.response_action(
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1593, in response_action
    response = func(self, request, queryset)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/actions.py", line 39, in delete_selected
    ) = modeladmin.get_deleted_objects(queryset, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2101, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 154, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 221, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 207, in _nested
    ret = [format_callback(obj)]
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 129, in format_callback
    no_edit_link = "%s: %s" % (capfirst(opts.verbose_name), obj)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py", line 24, in __str__
    return f"{self.name} {self.last_name}"
AttributeError: 'UserProfile' object has no attribute 'last_name'
[2024-09-13 16:44:16] [ERROR] [django.server:212] "POST /admin/service/userprofile/ HTTP/1.1" 500 1492
[2024-09-13 16:44:18] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11694
[2024-09-13 16:45:40] [ERROR] [django.request:241] Internal Server Error: /admin/service/userprofile/1/change/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py", line 24, in __str__
    return f"{self.name} {self.last_name}"
AttributeError: 'UserProfile' object has no attribute 'last_name'
[2024-09-13 16:45:40] [ERROR] [django.server:212] "GET /admin/service/userprofile/1/change/ HTTP/1.1" 500 1492
[2024-09-13 16:45:41] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11694
[2024-09-13 16:46:22] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py changed, reloading.
[2024-09-13 16:46:22] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:47:29] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 16:47:29] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:48:03] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/admin.py changed, reloading.
[2024-09-13 16:48:03] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:48:23] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:48:28] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-13 16:48:28] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:48:30] [ERROR] [django.request:241] Internal Server Error: /admin/service/userprofile/2/change/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py", line 24, in __str__
    return f"{self.name} {self.last_name}"
AttributeError: 'UserProfile' object has no attribute 'last_name'
[2024-09-13 16:48:30] [ERROR] [django.server:212] "GET /admin/service/userprofile/2/change/ HTTP/1.1" 500 1492
[2024-09-13 16:50:28] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/models.py changed, reloading.
[2024-09-13 16:50:28] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:50:37] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:50:41] [INFO] [django.server:212] "GET /admin/service/userprofile/2/home HTTP/1.1" 301 0
[2024-09-13 16:50:41] [INFO] [django.server:212] "GET /admin/service/userprofile/2/home/ HTTP/1.1" 302 0
[2024-09-13 16:50:41] [INFO] [django.server:212] "GET /admin/service/userprofile/2/home/change/ HTTP/1.1" 302 0
[2024-09-13 16:50:41] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7329
[2024-09-13 16:50:41] [INFO] [django.server:212] "GET /static/admin/img/icon-alert.034cc7d8a67f.svg HTTP/1.1" 200 297
[2024-09-13 16:50:44] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7149
[2024-09-13 16:50:45] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-13 16:50:45] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:50:47] [INFO] [django.server:212] "GET /admin/service/userprofile/1/change/ HTTP/1.1" 200 14535
[2024-09-13 16:50:47] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:50:47] [INFO] [django.server:212] "GET /static/admin/img/icon-viewlink.41eb31f7826e.svg HTTP/1.1" 200 326
[2024-09-13 16:50:52] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-13 16:50:53] [INFO] [django.server:212] "GET /admin/service/userprofile/2/change/ HTTP/1.1" 200 14532
[2024-09-13 16:50:53] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:50:54] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-13 16:50:58] [INFO] [django.server:212] "POST /admin/service/userprofile/ HTTP/1.1" 200 8339
[2024-09-13 16:50:59] [INFO] [django.server:212] "POST /admin/service/userprofile/ HTTP/1.1" 302 0
[2024-09-13 16:50:59] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11679
[2024-09-13 16:50:59] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:51:10] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:51:10] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:51:13] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:51:13] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:51:26] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:51:26] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:51:28] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:51:28] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:54:15] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 16:54:16] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:54:22] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:54:22] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:54:35] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:54:35] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-13 16:54:35] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-13 16:54:35] [INFO] [django.server:212] "GET /static/js/login.e1e08cd265ab.js HTTP/1.1" 200 1528
[2024-09-13 16:54:36] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-13 16:54:51] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:54:51] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:54:57] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:54:57] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:55:05] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:55:05] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:55:06] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 9854
[2024-09-13 16:55:06] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:55:06] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:55:06] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:57:11] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 16:57:12] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 16:57:15] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 16:57:29] [INFO] [service.views:134] Received POST request for signup
[2024-09-13 16:57:29] [WARNING] [service.views:156] Username already exists
[2024-09-13 16:57:29] [WARNING] [django.request:241] Bad Request: /signup_api/
[2024-09-13 16:57:29] [WARNING] [django.server:212] "POST /signup_api/ HTTP/1.1" 400 56
[2024-09-13 16:57:48] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:57:48] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:57:50] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 16:57:50] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:57:50] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 9854
[2024-09-13 16:57:50] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:57:51] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12224
[2024-09-13 16:57:51] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:57:59] [INFO] [django.server:212] "POST /admin/auth/user/ HTTP/1.1" 200 8298
[2024-09-13 16:58:00] [INFO] [django.server:212] "POST /admin/auth/user/ HTTP/1.1" 302 0
[2024-09-13 16:58:00] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 11946
[2024-09-13 16:58:00] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:58:04] [INFO] [service.views:134] Received POST request for signup
[2024-09-13 16:58:05] [ERROR] [service.views:187] Error occurred: UNIQUE constraint failed: service_userprofile.user_id
[2024-09-13 16:58:05] [ERROR] [django.request:241] Internal Server Error: /signup_api/
[2024-09-13 16:58:05] [ERROR] [django.server:212] "POST /signup_api/ HTTP/1.1" 500 93
[2024-09-13 16:58:29] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-13 16:58:29] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:58:30] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-13 16:58:30] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:58:32] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-13 16:58:32] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 16:59:21] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-13 16:59:21] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 16:59:21] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-13 16:59:32] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 302 0
[2024-09-13 16:59:32] [INFO] [django.server:212] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3791
[2024-09-13 16:59:32] [INFO] [django.server:212] "GET /static/admin/css/login.586129c60a93.css HTTP/1.1" 200 310
[2024-09-13 16:59:34] [INFO] [django.server:212] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 3952
[2024-09-13 16:59:40] [INFO] [django.server:212] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2024-09-13 16:59:40] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7667
[2024-09-13 16:59:40] [INFO] [django.server:212] "GET /static/admin/img/icon-deletelink.564ef9dc3854.svg HTTP/1.1" 200 195
[2024-09-13 16:59:42] [INFO] [django.server:212] "POST /admin/logout/ HTTP/1.1" 200 3654
[2024-09-13 16:59:49] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 17:01:01] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 17:02:39] [INFO] [django.server:212] "POST /admin/auth/user/ HTTP/1.1" 200 8430
[2024-09-13 17:02:40] [INFO] [django.server:212] "POST /admin/auth/user/ HTTP/1.1" 302 0
[2024-09-13 17:02:40] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 11946
[2024-09-13 17:02:40] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 17:02:41] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 17:02:41] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 17:02:43] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 11812
[2024-09-13 17:02:43] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 17:02:44] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11537
[2024-09-13 17:02:44] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 17:02:45] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 11812
[2024-09-13 17:02:45] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-13 17:03:19] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 17:03:19] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 17:03:31] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-13 17:03:31] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-13 17:03:33] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-13 17:03:49] [INFO] [django.server:212] "POST /signup_api/ HTTP/1.1" 200 74
[2024-09-13 17:03:49] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-13 17:03:49] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 04:12:10] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:12:20] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1839
[2024-09-14 04:12:20] [INFO] [django.server:212] "GET /static/css/faqs.981cb75cd138.css HTTP/1.1" 200 960
[2024-09-14 04:12:20] [INFO] [django.server:212] "GET /static/js/faqs.c1b3b40dff80.js HTTP/1.1" 200 995
[2024-09-14 04:12:20] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-14 04:12:20] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-14 04:12:21] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:12:21] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 18
[2024-09-14 04:12:21] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:20:22] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 302 0
[2024-09-14 04:20:22] [INFO] [django.server:212] "GET /home HTTP/1.1" 301 0
[2024-09-14 04:20:22] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-14 04:20:22] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 04:20:22] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-14 04:20:22] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-14 04:20:25] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 302 0
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3791
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /static/admin/css/dark_mode.ef27a31af300.css HTTP/1.1" 200 669
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /static/admin/css/base.64976e0f7339.css HTTP/1.1" 200 4149
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /static/admin/css/nav_sidebar.269a1bd44627.css HTTP/1.1" 200 625
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /static/admin/css/login.586129c60a93.css HTTP/1.1" 200 310
[2024-09-14 04:20:26] [INFO] [django.server:212] "GET /static/admin/css/responsive.107cd2690311.css HTTP/1.1" 200 2963
[2024-09-14 04:20:26] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-14 04:20:32] [INFO] [django.server:212] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2024-09-14 04:20:32] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 7905
[2024-09-14 04:20:32] [INFO] [django.server:212] "GET /static/admin/css/dashboard.e90f2068217b.css HTTP/1.1" 200 185
[2024-09-14 04:20:32] [INFO] [django.server:212] "GET /static/admin/img/icon-addlink.d519b3bab011.svg HTTP/1.1" 200 178
[2024-09-14 04:20:32] [INFO] [django.server:212] "GET /static/admin/img/icon-changelink.18d2fd706348.svg HTTP/1.1" 200 252
[2024-09-14 04:20:32] [INFO] [django.server:212] "GET /static/admin/img/icon-deletelink.564ef9dc3854.svg HTTP/1.1" 200 195
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/img/search.7cf54ff789c6.svg HTTP/1.1" 200 241
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/img/icon-yes.d2f9f035226a.svg HTTP/1.1" 200 242
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/img/icon-no.439e821418cd.svg HTTP/1.1" 200 257
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/css/changelists.9237a1ac391b.css HTTP/1.1" 200 1274
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/js/filters.0e360b7a9f80.js HTTP/1.1" 200 392
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/js/jquery.init.b7781a0897fc.js HTTP/1.1" 200 194
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/img/tooltag-add.e59d620a9742.svg HTTP/1.1" 200 182
[2024-09-14 04:20:35] [INFO] [django.server:212] "GET /static/admin/img/sorting-icons.3a097b59f104.svg HTTP/1.1" 200 329
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /admin/auth/user/1/change/ HTTP/1.1" 200 32991
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/SelectFilter2.bdb8d0cc579e.js HTTP/1.1" 200 2460
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/inlines.22d4d93c00b4.js HTTP/1.1" 200 3154
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/SelectBox.7d3ce5a98007.js HTTP/1.1" 200 844
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/css/forms.3b181cba6653.css HTTP/1.1" 200 1879
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/calendar.f8a5d055eb33.js HTTP/1.1" 200 1826
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/admin/DateTimeShortcuts.9f6e209cebca.js HTTP/1.1" 200 3030
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/change_form.9d8ca4f96b75.js HTTP/1.1" 200 243
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/js/prepopulate_init.6cac7f3105b8.js HTTP/1.1" 200 231
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/css/widgets.0a3765e806b3.css HTTP/1.1" 200 2142
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/img/icon-unknown-alt.81536e128bb6.svg HTTP/1.1" 200 345
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/img/icon-unknown.a18cb4398978.svg HTTP/1.1" 200 345
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/img/selector-icons.b4555096cea2.svg HTTP/1.1" 200 702
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/img/icon-calendar.ac7aea671bea.svg HTTP/1.1" 200 411
[2024-09-14 04:20:37] [INFO] [django.server:212] "GET /static/admin/img/icon-clock.e1d4dfac3f2b.svg HTTP/1.1" 200 329
[2024-09-14 04:20:40] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-14 04:20:41] [INFO] [django.server:212] "GET /admin/auth/user/4/change/ HTTP/1.1" 200 32962
[2024-09-14 04:20:41] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:20:44] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-14 04:20:46] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-14 04:20:46] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:20:48] [INFO] [django.server:212] "GET /admin/service/userprofile/4/change/ HTTP/1.1" 200 14532
[2024-09-14 04:20:48] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:20:48] [INFO] [django.server:212] "GET /static/admin/img/icon-viewlink.41eb31f7826e.svg HTTP/1.1" 200 326
[2024-09-14 04:20:52] [INFO] [django.server:212] "GET /admin/service/userprofile/ HTTP/1.1" 200 11842
[2024-09-14 04:20:53] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-14 04:20:53] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:21:57] [INFO] [django.utils.autoreload:266] /home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py changed, reloading.
[2024-09-14 04:21:57] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:22:08] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1835
[2024-09-14 04:22:09] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:22:09] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:22:09] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:22:21] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1835
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /static/css/faqs.776bc8010552.css HTTP/1.1" 200 979
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /static/js/faqs.249ebb5ab730.js HTTP/1.1" 200 994
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:22:23] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:22:31] [INFO] [django.server:212] "POST /logout/ HTTP/1.1" 200 17
[2024-09-14 04:22:31] [WARNING] [django.request:241] Not Found: /faqs/{% url 'home' %}
[2024-09-14 04:22:31] [WARNING] [django.server:212] "GET /faqs/%7B%%20url%20'home'%20%%7D HTTP/1.1" 404 1169
[2024-09-14 04:22:31] [INFO] [django.server:212] "GET /static/css/404.e6b0fe855dd5.css HTTP/1.1" 200 527
[2024-09-14 04:27:27] [WARNING] [django.request:241] Not Found: /faqs/{% url 'home' %}
[2024-09-14 04:27:27] [WARNING] [django.server:212] "GET /faqs/%7B%%20url%20'home'%20%%7D HTTP/1.1" 404 1169
[2024-09-14 04:27:29] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:27:32] [WARNING] [django.request:241] Not Found: /faqs/{% url 'login' %}
[2024-09-14 04:27:32] [WARNING] [django.server:212] "GET /faqs/%7B%%20url%20'login'%20%%7D HTTP/1.1" 404 1169
[2024-09-14 04:28:42] [ERROR] [django.request:241] Internal Server Error: /faqs/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 292, in faqs
    return render(request, 'faqs.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
[2024-09-14 04:28:42] [ERROR] [django.server:212] "GET /faqs/ HTTP/1.1" 500 1492
[2024-09-14 04:29:12] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1909
[2024-09-14 04:29:12] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:29:12] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:29:15] [WARNING] [django.request:241] Not Found: /faqs/{% url 'login' %}
[2024-09-14 04:29:15] [WARNING] [django.server:212] "GET /faqs/%7B%%20url%20'login'%20%%7D HTTP/1.1" 404 1169
[2024-09-14 04:29:53] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1868
[2024-09-14 04:29:53] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:29:53] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:30:03] [WARNING] [django.request:241] Not Found: /faqs/{% url 'login' %}
[2024-09-14 04:30:03] [WARNING] [django.server:212] "GET /faqs/%7B%%20url%20'login'%20%%7D HTTP/1.1" 404 1169
[2024-09-14 04:30:09] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-14 04:30:09] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 04:31:27] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:31:30] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1910
[2024-09-14 04:31:30] [INFO] [django.server:212] "GET /static/js/faqs.8acc2a395fef.js HTTP/1.1" 200 976
[2024-09-14 04:31:31] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:31:31] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:31:33] [INFO] [django.server:212] "GET /login HTTP/1.1" 301 0
[2024-09-14 04:31:33] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-14 04:31:33] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-14 04:31:42] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-14 04:31:42] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-14 04:31:42] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 04:31:42] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-14 04:31:49] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1910
[2024-09-14 04:31:49] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:31:49] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:31:49] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:31:57] [INFO] [django.server:212] "POST /logout/ HTTP/1.1" 200 17
[2024-09-14 04:31:57] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-14 04:31:57] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 04:32:01] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1910
[2024-09-14 04:32:01] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:32:01] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:33:15] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 04:33:15] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:33:15] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:35:22] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:35:24] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 04:35:24] [INFO] [django.server:212] "GET /static/css/faqs.95b9b6bfdb15.css HTTP/1.1" 200 973
[2024-09-14 04:35:24] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 04:35:24] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 108
[2024-09-14 04:35:29] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 302 0
[2024-09-14 04:35:29] [INFO] [django.server:212] "GET /admin/login/?next=/admin/auth/user/ HTTP/1.1" 200 4292
[2024-09-14 04:35:36] [INFO] [django.server:212] "POST /admin/login/?next=/admin/auth/user/ HTTP/1.1" 302 0
[2024-09-14 04:35:36] [INFO] [django.server:212] "GET /admin/auth/user/ HTTP/1.1" 200 12222
[2024-09-14 04:35:36] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:35:39] [INFO] [django.server:212] "GET /admin/service/faq/ HTTP/1.1" 200 11091
[2024-09-14 04:35:39] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:16] [INFO] [django.server:212] "POST /admin/service/faq/ HTTP/1.1" 200 8296
[2024-09-14 04:39:16] [INFO] [django.server:212] "GET /static/admin/js/cancel.ecc4c5ca7b32.js HTTP/1.1" 200 359
[2024-09-14 04:39:17] [INFO] [django.server:212] "POST /admin/service/faq/ HTTP/1.1" 302 0
[2024-09-14 04:39:17] [INFO] [django.server:212] "GET /admin/service/faq/ HTTP/1.1" 200 9599
[2024-09-14 04:39:17] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:18] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9667
[2024-09-14 04:39:18] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:24] [INFO] [django.server:212] "POST /admin/service/faq/add/ HTTP/1.1" 302 0
[2024-09-14 04:39:24] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9912
[2024-09-14 04:39:24] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:35] [INFO] [django.server:212] "POST /admin/service/faq/add/ HTTP/1.1" 302 0
[2024-09-14 04:39:35] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9912
[2024-09-14 04:39:35] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:50] [INFO] [django.server:212] "POST /admin/service/faq/add/ HTTP/1.1" 302 0
[2024-09-14 04:39:50] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9922
[2024-09-14 04:39:50] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:39:56] [INFO] [django.server:212] "POST /admin/service/faq/add/ HTTP/1.1" 302 0
[2024-09-14 04:39:56] [INFO] [django.server:212] "GET /admin/service/faq/add/ HTTP/1.1" 200 9928
[2024-09-14 04:39:56] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:40:06] [INFO] [django.server:212] "POST /admin/service/faq/add/ HTTP/1.1" 302 0
[2024-09-14 04:40:06] [INFO] [django.server:212] "GET /admin/service/faq/ HTTP/1.1" 200 12539
[2024-09-14 04:40:06] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 04:40:08] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 04:40:08] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-14 04:40:08] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:40:08] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:41:35] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:41:37] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 04:41:37] [INFO] [django.server:212] "GET /static/css/faqs.279aa674f12f.css HTTP/1.1" 200 965
[2024-09-14 04:41:37] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-14 04:41:37] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:41:37] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:42:25] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 04:42:27] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 04:42:27] [INFO] [django.server:212] "GET /static/css/faqs.4a4cf4e35221.css HTTP/1.1" 200 964
[2024-09-14 04:42:27] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-14 04:42:27] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 04:42:27] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 04:42:59] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[2024-09-14 04:42:59] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-14 06:49:45] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 06:49:50] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 9703
[2024-09-14 06:49:52] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 10483
[2024-09-14 06:49:52] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 06:49:54] [INFO] [django.server:212] "GET /admin/service/task/add/ HTTP/1.1" 200 12949
[2024-09-14 06:49:54] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-14 06:52:25] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 06:52:30] [INFO] [django.server:212] "GET / HTTP/1.1" 200 4075
[2024-09-14 06:52:30] [INFO] [django.server:212] "GET /static/css/home.d7116df7a79a.css HTTP/1.1" 200 1674
[2024-09-14 06:52:30] [INFO] [django.server:212] "GET /static/js/home.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-14 06:52:30] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:52:30] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:53:19] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:53:19] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:53:19] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:54:02] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 06:54:04] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:54:04] [INFO] [django.server:212] "GET /static/css/home.54c163179281.css HTTP/1.1" 200 1670
[2024-09-14 06:54:04] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:54:04] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:54:50] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 06:55:05] [INFO] [django.server:212] "GET / HTTP/1.1" 200 4075
[2024-09-14 06:55:05] [INFO] [django.server:212] "GET /static/css/home.66baabe947b9.css HTTP/1.1" 200 1666
[2024-09-14 06:55:05] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-14 06:55:05] [INFO] [django.server:212] "GET /static/js/home.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-14 06:55:06] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:55:06] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:55:11] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:55:11] [INFO] [django.server:212] "GET /static/css/home.66baabe947b9.css HTTP/1.1" 200 1666
[2024-09-14 06:55:11] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:55:12] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:55:19] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-14 06:55:19] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:55:19] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-14 06:55:19] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:55:23] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:55:23] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:55:23] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:55:26] [ERROR] [django.request:241] Internal Server Error: /profile/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 30, in profile
    return render(request, 'profile.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: profile.html
[2024-09-14 06:55:26] [ERROR] [django.server:212] "GET /profile/ HTTP/1.1" 500 1492
[2024-09-14 06:55:29] [ERROR] [django.request:241] Internal Server Error: /about_app/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 25, in about_app
    return render(request, 'about_app.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: about_app.html
[2024-09-14 06:55:29] [ERROR] [django.server:212] "GET /about_app/ HTTP/1.1" 500 1492
[2024-09-14 06:56:54] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-14 06:56:57] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:56:57] [INFO] [django.server:212] "GET /static/css/home.66baabe947b9.css HTTP/1.1" 200 1666
[2024-09-14 06:56:57] [INFO] [django.server:212] "GET /static/js/home.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-14 06:56:57] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-14 06:56:58] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-14 06:56:58] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:56:58] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-14 06:56:59] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-14 06:57:16] [INFO] [django.server:212] "POST /logout/ HTTP/1.1" 200 17
[2024-09-14 06:57:16] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:57:16] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-14 06:57:18] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-14 06:57:28] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-14 06:57:28] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-14 06:57:28] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-14 06:57:28] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:13:05] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 04:13:15] [INFO] [django.server:212] "GET / HTTP/1.1" 200 4075
[2024-09-15 04:13:15] [INFO] [django.server:212] "GET /static/css/home.1f570c16ece7.css HTTP/1.1" 200 1754
[2024-09-15 04:13:15] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-15 04:13:15] [INFO] [django.server:212] "GET /static/js/home.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-15 04:13:16] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-15 04:13:16] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:13:16] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7530
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/css/about_app.6f69f655374c.css HTTP/1.1" 200 1058
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/js/about_app.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/django.0f2ad6827a15.png HTTP/1.1" 200 1294
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/html.27b0afc8d706.png HTTP/1.1" 200 1028
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/postgresql.52231567c0fb.png HTTP/1.1" 200 1902
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/FAQ_API.b395df61f504.png HTTP/1.1" 200 61374
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/Django%20REST.94aac4077a1a.png HTTP/1.1" 200 14634
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/css.9d089bd0b10b.png HTTP/1.1" 200 1118
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/javascript.d8b359bb45cb.png HTTP/1.1" 200 630
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/Task_Management_API.c5308818e045.png HTTP/1.1" 200 66555
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/Overall_System_Diagram.d55fd658becd.png HTTP/1.1" 200 60639
[2024-09-15 04:13:21] [INFO] [django.server:212] "GET /static/img/User_Authentication_API.e03c64c4c979.png HTTP/1.1" 200 68593
[2024-09-15 04:13:22] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:13:22] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:15:39] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7611
[2024-09-15 04:15:39] [INFO] [django.server:212] "GET /static/img/python.6841951dd362.png HTTP/1.1" 200 871
[2024-09-15 04:15:39] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:15:39] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:20:36] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 04:20:39] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7711
[2024-09-15 04:20:39] [INFO] [django.server:212] "GET /static/css/about_app.e3a1cb9c1849.css HTTP/1.1" 200 1209
[2024-09-15 04:20:39] [INFO] [django.server:212] "GET /static/js/about_app.e1a96ecef89d.js HTTP/1.1" 200 730
[2024-09-15 04:20:39] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:20:39] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:21:14] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:21:15] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:21:15] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:23:53] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 04:23:56] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:23:56] [INFO] [django.server:212] "GET /static/css/home.7e795e8553c8.css HTTP/1.1" 200 1754
[2024-09-15 04:23:56] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:23:56] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:24:19] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:24:19] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:24:19] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:27:02] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4268
[2024-09-15 04:27:02] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:27:02] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:27:08] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4268
[2024-09-15 04:27:08] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:27:08] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:30:45] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 04:30:49] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:30:49] [INFO] [django.server:212] "GET /static/css/home.9a2b57f325b9.css HTTP/1.1" 200 1821
[2024-09-15 04:30:49] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:30:49] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:30:51] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:30:51] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:30:51] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:30:54] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:30:55] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:30:55] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:33:21] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 04:33:24] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:33:24] [INFO] [django.server:212] "GET /static/css/home.34f794cd2bbb.css HTTP/1.1" 200 1860
[2024-09-15 04:33:24] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:33:24] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:33:26] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4075
[2024-09-15 04:33:26] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 04:33:26] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 04:37:37] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'img/todo-benefits.png'
[2024-09-15 04:37:37] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-15 04:37:37] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-15 04:37:37] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-15 05:02:58] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:03:08] [INFO] [django.server:212] "GET /home HTTP/1.1" 301 0
[2024-09-15 05:03:08] [ERROR] [django.request:241] Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 22, in home
    return render(request, 'home.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'img/todo-benefits.png'
[2024-09-15 05:03:08] [ERROR] [django.server:212] "GET /home/ HTTP/1.1" 500 1492
[2024-09-15 05:03:49] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:03:52] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4869
[2024-09-15 05:03:52] [INFO] [django.server:212] "GET /static/css/home.d5d90e24807e.css HTTP/1.1" 200 1965
[2024-09-15 05:03:52] [INFO] [django.server:212] "GET /static/img/todo-benefits.e2eea31a5609.png HTTP/1.1" 200 883283
[2024-09-15 05:03:52] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:03:52] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:06:22] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:06:25] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4869
[2024-09-15 05:06:25] [INFO] [django.server:212] "GET /static/css/home.c7e28760cf5f.css HTTP/1.1" 200 2091
[2024-09-15 05:06:25] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:06:25] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:06:40] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:06:40] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:06:40] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:12:48] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:12:51] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:12:51] [INFO] [django.server:212] "GET /static/css/home.6ae93c39e3f7.css HTTP/1.1" 200 1983
[2024-09-15 05:12:51] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:12:51] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:18:55] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:18:57] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:18:57] [INFO] [django.server:212] "GET /static/css/home.6b83bcd72772.css HTTP/1.1" 200 1980
[2024-09-15 05:18:57] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:18:57] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:26:07] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:26:10] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:26:10] [INFO] [django.server:212] "GET /static/css/home.b572f8882c6f.css HTTP/1.1" 200 1992
[2024-09-15 05:26:10] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:26:10] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:27:48] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:27:48] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:27:48] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:29:11] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:29:11] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:29:11] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7711
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/python.6841951dd362.png HTTP/1.1" 200 871
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/django.0f2ad6827a15.png HTTP/1.1" 200 1294
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/js/about_app.e1a96ecef89d.js HTTP/1.1" 200 730
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/postgresql.52231567c0fb.png HTTP/1.1" 200 1902
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/Django%20REST.94aac4077a1a.png HTTP/1.1" 200 14634
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/html.27b0afc8d706.png HTTP/1.1" 200 1028
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/javascript.d8b359bb45cb.png HTTP/1.1" 200 630
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/css.9d089bd0b10b.png HTTP/1.1" 200 1118
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/Overall_System_Diagram.d55fd658becd.png HTTP/1.1" 200 60639
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/FAQ_API.b395df61f504.png HTTP/1.1" 200 61374
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/User_Authentication_API.e03c64c4c979.png HTTP/1.1" 200 68593
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /static/img/Task_Management_API.c5308818e045.png HTTP/1.1" 200 66555
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:29:14] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:29:34] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4863
[2024-09-15 05:29:34] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:29:34] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:31:43] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:31:46] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4963
[2024-09-15 05:31:46] [INFO] [django.server:212] "GET /static/css/home.d3b7beb823bf.css HTTP/1.1" 200 2119
[2024-09-15 05:31:46] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:31:46] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:31:54] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-15 05:32:07] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4963
[2024-09-15 05:32:07] [INFO] [django.server:212] "GET /static/css/home.d3b7beb823bf.css HTTP/1.1" 200 2119
[2024-09-15 05:32:07] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-15 05:32:07] [INFO] [django.server:212] "GET /static/js/home.0f61a6e15ad2.js HTTP/1.1" 200 634
[2024-09-15 05:32:08] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-15 05:32:08] [INFO] [django.server:212] "GET /static/img/todo-benefits.e2eea31a5609.png HTTP/1.1" 200 883283
[2024-09-15 05:32:08] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:32:08] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:32:09] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-15 05:32:30] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:32:33] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4963
[2024-09-15 05:32:33] [INFO] [django.server:212] "GET /static/js/home.8aa092528355.js HTTP/1.1" 200 730
[2024-09-15 05:32:33] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:32:33] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:34:51] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 5002
[2024-09-15 05:34:51] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:34:51] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:37:46] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:37:50] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-15 05:37:50] [INFO] [django.server:212] "GET /static/css/home.83fdf77555dd.css HTTP/1.1" 200 2144
[2024-09-15 05:37:50] [INFO] [django.server:212] "GET /static/js/home.01089d8529b4.js HTTP/1.1" 200 763
[2024-09-15 05:37:50] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:37:50] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:39:38] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-15 05:39:41] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-15 05:39:41] [INFO] [django.server:212] "GET /static/js/home.9e7c2373e1e9.js HTTP/1.1" 200 768
[2024-09-15 05:39:41] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:39:41] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:40:07] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-15 05:40:07] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:40:07] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:40:14] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-15 05:40:14] [INFO] [django.server:212] "GET /static/css/faqs.4a4cf4e35221.css HTTP/1.1" 200 964
[2024-09-15 05:40:14] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:40:14] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-15 05:40:14] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:40:19] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-15 05:40:19] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:40:19] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:40:23] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7711
[2024-09-15 05:40:23] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:40:23] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-15 05:40:30] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-15 05:40:30] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-15 05:40:30] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 03:29:02] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 302 0
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /home HTTP/1.1" 301 0
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /static/css/home.83fdf77555dd.css HTTP/1.1" 200 2144
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-16 03:29:06] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-16 03:29:07] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 03:29:07] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 03:29:29] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-16 03:40:58] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 03:41:01] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-16 03:41:01] [INFO] [django.server:212] "GET /static/css/home.2c2e0972640d.css HTTP/1.1" 200 2134
[2024-09-16 03:41:01] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 03:41:01] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 03:41:40] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 4987
[2024-09-16 03:41:40] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 03:41:40] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:01:31] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:01:34] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:01:34] [INFO] [django.server:212] "GET /static/css/home.361d828b2a00.css HTTP/1.1" 200 2414
[2024-09-16 04:01:35] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:01:35] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:07:42] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:07:44] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:07:44] [INFO] [django.server:212] "GET /static/css/home.b2464c3f0c42.css HTTP/1.1" 200 2406
[2024-09-16 04:07:44] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:07:44] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:10:35] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:10:38] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:10:38] [INFO] [django.server:212] "GET /static/css/home.4ef2c3485fe9.css HTTP/1.1" 200 2476
[2024-09-16 04:10:38] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:10:38] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:11:00] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:11:00] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:11:01] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:12:32] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:12:35] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:12:35] [INFO] [django.server:212] "GET /static/css/home.ec19d0243712.css HTTP/1.1" 200 2519
[2024-09-16 04:12:35] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:12:36] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:25:20] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:25:22] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:25:22] [INFO] [django.server:212] "GET /static/css/home.8dd2093626d5.css HTTP/1.1" 200 2574
[2024-09-16 04:25:23] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:25:23] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:32:47] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:32:50] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:32:50] [INFO] [django.server:212] "GET /static/css/home.a0193f52a437.css HTTP/1.1" 200 2577
[2024-09-16 04:32:50] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:32:50] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:34:09] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:34:09] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:34:09] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:34:20] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:34:20] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:34:20] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:42:13] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:42:17] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:42:17] [INFO] [django.server:212] "GET /static/css/home.0ff3a53fa678.css HTTP/1.1" 200 2590
[2024-09-16 04:42:17] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:42:17] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:47:57] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:48:02] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 6817
[2024-09-16 04:48:02] [INFO] [django.server:212] "GET /static/css/home.c3148ebbe41d.css HTTP/1.1" 200 2589
[2024-09-16 04:48:02] [INFO] [django.server:212] "GET /static/js/home.a85e03ecd8a8.js HTTP/1.1" 200 1118
[2024-09-16 04:48:02] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:48:02] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:48:26] [INFO] [django.server:212] "POST /tasks/create/ HTTP/1.1" 201 51
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /static/js/particles.08453b19a816.js HTTP/1.1" 200 313
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /static/js/home.a85e03ecd8a8.js HTTP/1.1" 200 1118
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /static/fav/favicon-16x16.20672376a414.png HTTP/1.1" 200 12014
[2024-09-16 04:49:29] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 302 0
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /static/img/logo.3e0c68070678.png HTTP/1.1" 200 127375
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:49:31] [INFO] [django.server:212] "GET /static/img/todo-benefits.e2eea31a5609.png HTTP/1.1" 200 883283
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /admin/ HTTP/1.1" 200 9703
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/css/dark_mode.ef27a31af300.css HTTP/1.1" 200 669
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/css/dashboard.e90f2068217b.css HTTP/1.1" 200 185
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/css/base.64976e0f7339.css HTTP/1.1" 200 4149
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/css/nav_sidebar.269a1bd44627.css HTTP/1.1" 200 625
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/css/responsive.107cd2690311.css HTTP/1.1" 200 2963
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/img/icon-addlink.d519b3bab011.svg HTTP/1.1" 200 178
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/img/icon-changelink.18d2fd706348.svg HTTP/1.1" 200 252
[2024-09-16 04:49:34] [INFO] [django.server:212] "GET /static/admin/img/icon-deletelink.564ef9dc3854.svg HTTP/1.1" 200 195
[2024-09-16 04:49:35] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-16 04:49:35] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 1169
[2024-09-16 04:49:36] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 12600
[2024-09-16 04:49:36] [INFO] [django.server:212] "GET /static/admin/css/changelists.9237a1ac391b.css HTTP/1.1" 200 1274
[2024-09-16 04:49:36] [INFO] [django.server:212] "GET /static/admin/js/filters.0e360b7a9f80.js HTTP/1.1" 200 392
[2024-09-16 04:49:36] [INFO] [django.server:212] "GET /static/admin/js/jquery.init.b7781a0897fc.js HTTP/1.1" 200 194
[2024-09-16 04:49:37] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 04:49:37] [INFO] [django.server:212] "GET /static/admin/img/search.7cf54ff789c6.svg HTTP/1.1" 200 241
[2024-09-16 04:49:37] [INFO] [django.server:212] "GET /static/admin/img/tooltag-add.e59d620a9742.svg HTTP/1.1" 200 182
[2024-09-16 04:49:42] [INFO] [django.server:212] "POST /tasks/create/ HTTP/1.1" 201 51
[2024-09-16 04:49:52] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 13052
[2024-09-16 04:49:52] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 04:49:52] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-16 04:49:57] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:49:57] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:49:57] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:50:29] [ERROR] [django.request:241] Internal Server Error: /profile/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 30, in profile
    return render(request, 'profile.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: profile.html
[2024-09-16 04:50:29] [ERROR] [django.server:212] "GET /profile/ HTTP/1.1" 500 1492
[2024-09-16 04:50:29] [INFO] [django.server:212] "GET /static/css/500.2a16a0a45b70.css HTTP/1.1" 200 807
[2024-09-16 04:50:29] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-16 04:50:30] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-16 04:50:36] [INFO] [django.server:212] "POST /admin/service/task/ HTTP/1.1" 200 8285
[2024-09-16 04:50:37] [INFO] [django.server:212] "GET /static/admin/js/cancel.ecc4c5ca7b32.js HTTP/1.1" 200 359
[2024-09-16 04:50:38] [INFO] [django.server:212] "POST /admin/service/task/ HTTP/1.1" 302 0
[2024-09-16 04:50:38] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 12734
[2024-09-16 04:50:38] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 04:50:38] [INFO] [django.server:212] "GET /static/admin/img/icon-yes.d2f9f035226a.svg HTTP/1.1" 200 242
[2024-09-16 04:51:06] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:51:06] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:51:06] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:26] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 04:52:28] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:52:28] [INFO] [django.server:212] "GET /static/css/home.e1ae94e78abb.css HTTP/1.1" 200 2597
[2024-09-16 04:52:28] [INFO] [django.server:212] "GET /static/js/home.a85e03ecd8a8.js HTTP/1.1" 200 1118
[2024-09-16 04:52:29] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:29] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:34] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:52:34] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:34] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:36] [INFO] [django.server:212] "GET /faqs/ HTTP/1.1" 200 1904
[2024-09-16 04:52:36] [INFO] [django.server:212] "GET /static/css/faqs.4a4cf4e35221.css HTTP/1.1" 200 964
[2024-09-16 04:52:36] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:36] [INFO] [django.server:212] "GET /faqs_api/ HTTP/1.1" 200 940
[2024-09-16 04:52:36] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:37] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:52:38] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:38] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /about_app/ HTTP/1.1" 200 7711
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/css/about_app.e3a1cb9c1849.css HTTP/1.1" 200 1209
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/django.0f2ad6827a15.png HTTP/1.1" 200 1294
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/css.9d089bd0b10b.png HTTP/1.1" 200 1118
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/js/about_app.e1a96ecef89d.js HTTP/1.1" 200 730
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/html.27b0afc8d706.png HTTP/1.1" 200 1028
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/python.6841951dd362.png HTTP/1.1" 200 871
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/postgresql.52231567c0fb.png HTTP/1.1" 200 1902
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/Django%20REST.94aac4077a1a.png HTTP/1.1" 200 14634
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/javascript.d8b359bb45cb.png HTTP/1.1" 200 630
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/FAQ_API.b395df61f504.png HTTP/1.1" 200 61374
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/User_Authentication_API.e03c64c4c979.png HTTP/1.1" 200 68593
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/Task_Management_API.c5308818e045.png HTTP/1.1" 200 66555
[2024-09-16 04:52:39] [INFO] [django.server:212] "GET /static/img/Overall_System_Diagram.d55fd658becd.png HTTP/1.1" 200 60639
[2024-09-16 04:52:45] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 04:52:45] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 04:52:45] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 05:31:12] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 05:31:15] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 05:31:15] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 05:31:15] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 05:31:23] [INFO] [django.server:212] "POST /logout/ HTTP/1.1" 200 17
[2024-09-16 05:31:23] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 05:31:23] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-16 05:31:35] [INFO] [django.server:212] "POST /tasks/create/ HTTP/1.1" 302 0
[2024-09-16 05:31:35] [WARNING] [django.request:241] Not Found: /accounts/login/
[2024-09-16 05:31:35] [WARNING] [django.server:212] "GET /accounts/login/?next=/tasks/create/ HTTP/1.1" 404 1169
[2024-09-16 05:31:44] [INFO] [django.server:212] "POST /tasks/create/ HTTP/1.1" 302 0
[2024-09-16 05:31:44] [WARNING] [django.request:241] Not Found: /accounts/login/
[2024-09-16 05:31:44] [WARNING] [django.server:212] "GET /accounts/login/?next=/tasks/create/ HTTP/1.1" 404 1169
[2024-09-16 05:32:09] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 05:32:10] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 05:32:10] [INFO] [django.server:212] "GET /static/js/home.bcf4f21bb1c9.js HTTP/1.1" 200 1210
[2024-09-16 05:32:10] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-16 05:32:12] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 27
[2024-09-16 05:32:12] [INFO] [django.server:212] "GET /login HTTP/1.1" 301 0
[2024-09-16 05:32:12] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4543
[2024-09-16 05:32:12] [INFO] [django.server:212] "GET /static/css/login.f674594db6bc.css HTTP/1.1" 200 1142
[2024-09-16 05:32:53] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 200 4659
[2024-09-16 05:33:04] [INFO] [django.server:212] "POST /login_api/ HTTP/1.1" 200 48
[2024-09-16 05:33:04] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 05:33:04] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 05:33:04] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 05:33:24] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 05:33:24] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 05:33:24] [INFO] [django.server:212] "POST /tasks/create/ HTTP/1.1" 201 51
[2024-09-16 05:33:29] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 13052
[2024-09-16 05:33:29] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 05:33:29] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-16 05:33:32] [INFO] [django.server:212] "GET /admin/service/task/2/change/ HTTP/1.1" 200 13193
[2024-09-16 05:33:32] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 05:33:33] [INFO] [django.server:212] "GET /static/admin/css/widgets.0a3765e806b3.css HTTP/1.1" 200 2142
[2024-09-16 05:33:33] [INFO] [django.server:212] "GET /static/admin/js/change_form.9d8ca4f96b75.js HTTP/1.1" 200 243
[2024-09-16 05:33:33] [INFO] [django.server:212] "GET /static/admin/js/prepopulate_init.6cac7f3105b8.js HTTP/1.1" 200 231
[2024-09-16 05:33:33] [INFO] [django.server:212] "GET /static/admin/img/icon-viewlink.41eb31f7826e.svg HTTP/1.1" 200 326
[2024-09-16 05:33:33] [WARNING] [django.request:241] Not Found: /favicon.ico
[2024-09-16 05:33:33] [WARNING] [django.server:212] "GET /favicon.ico HTTP/1.1" 404 1169
[2024-09-16 05:33:40] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 13052
[2024-09-16 05:33:40] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 05:33:43] [INFO] [django.server:212] "POST /admin/service/task/ HTTP/1.1" 200 8285
[2024-09-16 05:33:44] [INFO] [django.server:212] "POST /admin/service/task/ HTTP/1.1" 302 0
[2024-09-16 05:33:44] [INFO] [django.server:212] "GET /admin/service/task/ HTTP/1.1" 200 12734
[2024-09-16 05:33:44] [INFO] [django.server:212] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[2024-09-16 05:57:54] [INFO] [django.utils.autoreload:668] Watching for file changes with StatReloader
[2024-09-16 05:57:57] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 05:57:57] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 05:57:57] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
[2024-09-16 05:58:01] [INFO] [django.server:212] "GET /forgot/ HTTP/1.1" 200 1996
[2024-09-16 05:58:01] [INFO] [django.server:212] "GET /static/css/forgot.f89c64031dbb.css HTTP/1.1" 200 897
[2024-09-16 05:58:01] [INFO] [django.server:212] "GET /static/js/forgot.60e0c6bcdeee.js HTTP/1.1" 200 661
[2024-09-16 05:59:00] [INFO] [django.server:212] "GET /forgot/ HTTP/1.1" 200 2029
[2024-09-16 05:59:51] [ERROR] [django.request:241] Internal Server Error: /forgot/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 217, in forgot
    return render(request, 'forgot.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
[2024-09-16 05:59:51] [ERROR] [django.server:212] "GET /forgot/ HTTP/1.1" 500 1492
[2024-09-16 05:59:51] [INFO] [django.server:212] "GET /static/js/500.2f833874b2f9.js HTTP/1.1" 200 108
[2024-09-16 06:00:01] [ERROR] [django.request:241] Internal Server Error: /forgot/
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ghost/Desktop/project/github_clone/to_do_list/to_do_list/service/views.py", line 217, in forgot
    return render(request, 'forgot.html')
  File "/home/ghost/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ghost/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login_sining' not found. 'login_sining' is not a valid view function or pattern name.
[2024-09-16 06:00:01] [ERROR] [django.server:212] "GET /forgot/ HTTP/1.1" 500 1492
[2024-09-16 06:00:23] [INFO] [django.server:212] "GET /forgot/ HTTP/1.1" 200 2070
[2024-09-16 06:00:25] [INFO] [django.server:212] "GET /login/ HTTP/1.1" 302 0
[2024-09-16 06:00:25] [INFO] [django.server:212] "GET /home/ HTTP/1.1" 200 7012
[2024-09-16 06:00:25] [INFO] [django.server:212] "GET /check_authenticated/ HTTP/1.1" 200 26
[2024-09-16 06:00:25] [INFO] [django.server:212] "GET /get_user_profile/ HTTP/1.1" 200 21
